const allPosts = [
  {
    id: 1,
    postTitle: 'Exploring the Majestic Himalayas',
    postTag: 'himalayas-trek',
    postLocation: 'Nepal',
    postCategory: 'Travel',
    postNature: 'Natural',
    postImage: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRO-ihD3U2tJk0LzZ6O3y5jvkr-hrLZQb9wIQ&s',
    postContent:
      'The Himalayas, a vast mountain range stretching across multiple countries, offers breathtaking landscapes and thrilling trekking experiences. From Everest Base Camp to Annapurna Circuit, adventurers flock here for the ultimate challenge. The serene monasteries, diverse wildlife, and stunning vistas make this a must-visit destination for nature lovers and trekkers alike.',
    autherId: 'user_101',
    commentId: 'comment_201',
    likedId: 'like_301',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 2,
    postTitle: 'The Great Wall of China: A Walk Through History',
    postTag: 'great-wall-china',
    postLocation: 'China',
    postCategory: 'History',
    postNature: 'Manmade',
    postImage: 'https://cdn.britannica.com/82/94382-050-20CF23DB/Great-Wall-of-China-Beijing.jpg',
    postContent:
      'The Great Wall of China is one of the most incredible architectural marvels ever built. Stretching over 13,000 miles, this ancient fortification was designed to protect Chinese states from invasions. Walking along the wall, one can witness stunning landscapes, experience local culture, and appreciate the sheer determination it took to construct this legendary structure.',
    autherId: 'user_102',
    commentId: 'comment_202',
    likedId: 'like_302',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 3,
    postTitle: 'Amazon Rainforest: The Lungs of the Earth',
    postTag: 'amazon-rainforest',
    postLocation: 'Brazil',
    postCategory: 'Nature',
    postNature: 'Natural',
    postImage: 'https://www.vedantu.com/question-sets/3617257a-2b34-4562-a7dc-02febc2d4c832086141092081577447.png',
    postContent:
      "The Amazon Rainforest is a vast ecosystem that plays a critical role in regulating the Earth's oxygen levels. Home to millions of species, including jaguars, anacondas, and toucans, it offers an unparalleled biodiversity experience. However, deforestation remains a major threat, and conservation efforts are vital to preserve this ecological wonder.",
    autherId: 'user_103',
    commentId: 'comment_203',
    likedId: 'like_303',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 4,
    postTitle: 'The Colosseum: A Glimpse into Ancient Rome',
    postTag: 'colosseum-rome',
    postLocation: 'Italy',
    postCategory: 'Architecture',
    postNature: 'Manmade',
    postImage: 'https://cdn.britannica.com/36/162636-050-932C5D49/Colosseum-Rome-Italy.jpg',
    postContent:
      "The Colosseum, an iconic Roman amphitheater, is a testament to ancient engineering brilliance. Built in 80 AD, it hosted gladiator battles, public spectacles, and theatrical performances. Today, it stands as a UNESCO World Heritage site, attracting millions of visitors eager to explore Rome's rich history and culture.",
    autherId: 'user_104',
    commentId: 'comment_204',
    likedId: 'like_304',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 5,
    postTitle: 'Santorini: The White and Blue Paradise',
    postTag: 'santorini-travel',
    postLocation: 'Greece',
    postCategory: 'Travel',
    postNature: 'Natural',
    postImage: 'https://images.stockcake.com/public/7/3/3/73333f99-0d8d-4dab-85d3-a7cd08b13a9b_large/santorini-sunset-paradise-stockcake.jpg',
    postContent:
      'Santorini is a dream destination known for its white-washed buildings, blue domes, and breathtaking sunsets. Whether exploring ancient ruins, enjoying local delicacies, or relaxing on black sand beaches, this Greek island offers an unforgettable experience to every traveler.',
    autherId: 'user_105',
    commentId: 'comment_205',
    likedId: 'like_305',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 6,
    postTitle: 'Machu Picchu: The Lost City of the Incas',
    postTag: 'machu-picchu',
    postLocation: 'Peru',
    postCategory: 'History',
    postNature: 'Manmade',
    postImage: 'https://media-cldnry.s-nbcnews.com/image/upload/t_fit-1500w,f_auto,q_auto:best/MSNBC/Components/Photo/_new/machu-picchu-600x450.jpg',
    postContent:
      'Hidden in the Andes Mountains, Machu Picchu is one of the most famous archaeological sites in the world. Built by the Incas in the 15th century, it remains a mystery regarding its exact purpose. Whether you hike the Inca Trail or take the train, witnessing this UNESCO World Heritage Site is an awe-inspiring experience.',
    autherId: 'user_106',
    commentId: 'comment_206',
    likedId: 'like_306',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 7,
    postTitle: 'The Grand Canyon: A Geological Wonder',
    postTag: 'grand-canyon',
    postLocation: 'USA',
    postCategory: 'Nature',
    postNature: 'Natural',
    postImage: 'https://sevennaturalwonders.org/wp-content/uploads/2023/11/Grand-Canyon-colorado-river.jpg',
    postContent:
      'The Grand Canyon, carved by the Colorado River, is one of the most impressive natural landscapes in the world. With its deep valleys, layered rock formations, and stunning viewpoints, it attracts millions of visitors annually for hiking, rafting, and breathtaking sunset views.',
    autherId: 'user_107',
    commentId: 'comment_207',
    likedId: 'like_307',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];

export default allPosts;
